USE_LR_PARSER

prog
(* ======================================================================================================= *)
<prog>               ::= <stmt_list> "."                                                                .